name: Github Actions v3 token test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-and-upstream:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "pypy3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pytest-cov
          pip install requests
      - name: Run Script
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true 
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
